config/routes.rb
MyFirstMusic::Application.routes.draw do
  resources :user_uploads
  resources :uploads
  resources :user_uploads, :path=>'playlist'
  root :to => 'user_uploads#index'
  devise_for :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
       user ||= User.new # guest user (not logged in)
       #Role.find(:id=>UsersRole.find_by(:user_id=>current_user.id).role_id)
       if user.role? :admin
         can :read, :all
         can :update, :all
         can :destroy, :all
         can :create, :all
         #can :manage, :all
       elsif user.role? :user
         can :read, :all
         can :update, :self
         can :destroy, :self
         can :create, :all
         #can :read, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
  has_many :users_roles
  has_many :users, :through => :users_roles
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  has_many :user_uploads
  has_many :users, :through => :user_uploads
  attr_accessible :upload
  has_attached_file :upload
  attr_accessible :users
  include Rails.application.routes.url_helpers

  def to_jq_upload
    {
      "name" => read_attribute(:upload_file_name),
      "size" => read_attribute(:upload_file_size),
      "url" => upload.url(:original),
      #"url" => upload.url('/system'),
      "delete_url" => upload_path(self),
      #"delete_url" => upload_path('/system'),
      "delete_type" => "DELETE" 
    }
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  after_create :creat_users_role
  before_destroy :destroy_users_role
  # Setup accessible (or protected) attributes for your model
  # attr_accessible :title, :body
  #private
  #def create_role
    #self.roles << Role.find_by_name(:user)
  #end
  def creat_users_role
    temp=UsersRole.new
    temp.user_id=self.id
    temp.role_id=Role.find_by_name('user').id
    self.users_roles<<temp
  end
  def destroy_users_role
    self.users_roles.find_by_user_id(self.id).destroy
  end
  def role
    temp=UsersRole.find_by_user_id(self.id)
    if temp
      Role.find_by_id(temp.role_id).name
    end
  end
  def role?(role)
    #return !!self.roles.find_by_name(role.to_s.camelize)
    #!!self.users_roles.role.find_by_name(role.to_s.camelize)
    #temp=UsersRole.find_by_user_id(self.id)
    #if temp
    #  Role.find_by_id(temp.role_id).name==role.to_s
    #end
    self.role==role.to_s
  end
  has_many :users_roles
  has_many :roles, :through => :users_roles
  has_many :user_uploads
  has_many :uploads, :through => :user_uploads
end

app/models/user_upload.rb
class UserUpload < ActiveRecord::Base
  belongs_to :user
  belongs_to :upload
  attr_accessible :user, :upload
end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  # GET /uploads
  # GET /uploads.json
  def index
    if user_signed_in?
      @uploads = current_user.uploads
      #Upload.where(:users. => current_user)
    else
      @uploads=nil
    end
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @uploads.map{|upload| upload.to_jq_upload } }

      end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = Upload.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = Upload.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(params[:upload])
    respond_to do |format|
      if @upload.save
        UserUpload.new(:user=>current_user,:upload=>@upload).save
        format.html {
          render :json => [@upload.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json { render json: {files: [@upload.to_jq_upload]}, status: :created, location: @upload }
      else
        format.html { render action: "new" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = Upload.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = Upload.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_uploads_controller.rb
class UserUploadsController < ApplicationController
  # GET /user_uploads
  # GET /user_uploads.json
  def index
    if user_signed_in?
      @uploads = current_user.uploads
      #Upload.where(:users. => current_user)
    else
      @uploads=nil
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads.map{|upload| upload.to_jq_upload } }

    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end


  def resource
    @resource ||= User.new
  end


  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/user_uploads_helper.rb
module UserUploadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstMusic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
  <%= render "shared/links" %>
</header>
<%= yield %>
</body>
</html>

app/views/shared/_links.html.erb
<ul>
  <% if user_signed_in? %>
      <li>Your name: <%= link_to current_user.username, edit_user_registration_path%> </li>
      <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </li>
      <li><%= link_to "Playlist", user_uploads_path %></li>
      <li><%= link_to "Edit Playlist", uploads_path%></li>
  <% else %>
      <li><%= link_to "Registration", new_user_registration_path%> </li>
      <li><%= link_to "Sign in", new_user_session_path%> </li>
  <% end %>
</ul>

app/views/uploads/index.html.erb
<% if user_signed_in? %>
<div class="container">
  <h2>Upload file</h2>
  <%= form_for Upload.new, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span7">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Add files...</span>
          <%= f.file_field :upload %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Start upload</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Cancel upload</span>
        </button>
        <button type="button" class="btn btn-danger delete">
          <i class="icon-trash icon-white"></i>
          <span>Delete</span>
        </button>
        <input type="checkbox" class="toggle">
      </div>
      <div class="span5">
        <!-- The global progress bar -->
        <div class="progress progress-success progress-striped active fade">
          <div class="bar" style="width:0%;"></div>
        </div>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody>
    </table>
  <% end %>

</div>
<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>{%=locale.fileupload.start%}</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-warning">
        <i class="icon-ban-circle icon-white"></i>
        <span>{%=locale.fileupload.cancel%}</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
  {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
      {% if (file.error) { %}
        <td></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
        {% } else { %}
        <td class="preview">{% if (file.thumbnail_url) { %}
          <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery" download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
          {% } %}</td>
        <td class="name">
          <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
        </td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        <td colspan="2"></td>
        {% } %}
      <td class="delete">
        <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}">
          <i class="icon-trash icon-white"></i>
          <span>{%=locale.fileupload.destroy%}</span>
        </button>
        <input type="checkbox" name="delete" value="1">
      </td>
    </tr>
    {% } %}
</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      // 
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'), 
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>
<% else %>
    <h2>please login or register</h2>
<%end%>

app/views/user_uploads/index.html.erb
<div id='content'>
<h1>Playlist</h1>
<% if user_signed_in? %>
Volume:</b><input id="slide" type="range" min="1" max="100" step="1" value="50" onchange="threeSixtyPlayer.setVolume(this.value)">
<div id="audios"></div>
<script type="text/javascript" charset="utf-8">
    $(function () {
        $.getJSON('/uploads', function (files) {
            console.log(files);
            for(var i=0;i<files.length;i++){
               var main= $('<div class="ui360"></div>');
                var link=$('<a href="'+files[i].url+'">'+files[i].name+'</a>');
                main.append(link);
                $('#audios').append(main);
            }
        });
    });
</script>
<% else %>
    <h2>Please login or register</h2>
<%end%>
</div>